### ISSUE TITLE
Question: How to contribute to this plugin?

### ISSUE THREAD

**Issue by dinbtechit** [Cap-Cloud/Cap-Elasticsearch-Client#6]
Question: How to contribute to this plugin? is the source code open source? I want to be able to add a functionality to edit the documents directly.

**Comment by Cap-Cloud** [comment]
It now open source, branch community, you can fork it and add your functionality.
There is a problem, <runLineMarkerContributor language="ElasticsearchKql" .../> works will with IDEA 2020, but does not work with IDEA 2021, if you have time and resource, you can try to fix it.
Thanks!

**Comment by Cap-Cloud** [comment]
It now open source, branch community, you can fork it and add your functionality.
There is a problem, <runLineMarkerContributor language="ElasticsearchKql" .../> works well with IDEA 2020, but does not work with IDEA 2021, if you have time and resource, you can try to fix it.
Thanks!
